Resources:
  DatabaseQuestion7AA389D3:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: "N"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: BackendStack/Database/Question/Resource
  LambdaFunctionshelloFnServiceRoleEB80A9DC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: BackendStack/LambdaFunctions/helloFn/ServiceRole/Resource
  LambdaFunctionshelloFn78D97221:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18eS3BucketCFDE3952
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18eS3VersionKeyBCDB680B
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18eS3VersionKeyBCDB680B
      Handler: hello.main
      Role:
        Fn::GetAtt:
          - LambdaFunctionshelloFnServiceRoleEB80A9DC
          - Arn
      Runtime: nodejs12.x
    DependsOn:
      - LambdaFunctionshelloFnServiceRoleEB80A9DC
    Metadata:
      aws:cdk:path: BackendStack/LambdaFunctions/helloFn/Resource
      aws:asset:path: /Users/musicqpee/github/cloud-dashboard/backend/lambda
      aws:asset:property: Code
  Gatewayhello270BBC94:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: hello
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Resource
  GatewayhelloCloudWatchRoleD6B1D3E5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/CloudWatchRole/Resource
  GatewayhelloAccount5145D05C:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - GatewayhelloCloudWatchRoleD6B1D3E5
          - Arn
    DependsOn:
      - Gatewayhello270BBC94
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Account
  GatewayhelloDeployment12F5DE0Eecdf6ef226f42ff306807b06f95fc629:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: Gatewayhello270BBC94
      Description: Automatically created by the RestApi construct
    DependsOn:
      - GatewayhelloproxyANY577AF459
      - GatewayhelloproxyB07E0BCE
      - GatewayhelloANY5BB5497B
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Deployment/Resource
  GatewayhelloDeploymentStageprod042FD68F:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: Gatewayhello270BBC94
      DeploymentId:
        Ref: GatewayhelloDeployment12F5DE0Eecdf6ef226f42ff306807b06f95fc629
      StageName: prod
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/DeploymentStage.prod/Resource
  GatewayhelloproxyB07E0BCE:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - Gatewayhello270BBC94
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: Gatewayhello270BBC94
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Default/{proxy+}/Resource
  GatewayhelloproxyANYApiPermissionBackendStackGatewayhelloC14EA33BANYproxyAA2593B3:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LambdaFunctionshelloFn78D97221
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Gatewayhello270BBC94
            - /
            - Ref: GatewayhelloDeploymentStageprod042FD68F
            - /*/*
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Default/{proxy+}/ANY/ApiPermission.BackendStackGatewayhelloC14EA33B.ANY..{proxy+}
  GatewayhelloproxyANYApiPermissionTestBackendStackGatewayhelloC14EA33BANYproxy7A478907:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LambdaFunctionshelloFn78D97221
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Gatewayhello270BBC94
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Default/{proxy+}/ANY/ApiPermission.Test.BackendStackGatewayhelloC14EA33B.ANY..{proxy+}
  GatewayhelloproxyANY577AF459:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: GatewayhelloproxyB07E0BCE
      RestApiId:
        Ref: Gatewayhello270BBC94
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - LambdaFunctionshelloFn78D97221
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Default/{proxy+}/ANY/Resource
  GatewayhelloANYApiPermissionBackendStackGatewayhelloC14EA33BANY448195FD:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LambdaFunctionshelloFn78D97221
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Gatewayhello270BBC94
            - /
            - Ref: GatewayhelloDeploymentStageprod042FD68F
            - /*/
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Default/ANY/ApiPermission.BackendStackGatewayhelloC14EA33B.ANY..
  GatewayhelloANYApiPermissionTestBackendStackGatewayhelloC14EA33BANY419CFA94:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - LambdaFunctionshelloFn78D97221
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: Gatewayhello270BBC94
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Default/ANY/ApiPermission.Test.BackendStackGatewayhelloC14EA33B.ANY..
  GatewayhelloANY5BB5497B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - Gatewayhello270BBC94
          - RootResourceId
      RestApiId:
        Ref: Gatewayhello270BBC94
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - LambdaFunctionshelloFn78D97221
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: BackendStack/Gateway/hello/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.51.0,@aws-cdk/assets=1.51.0,@aws-cdk/aws-apigateway=1.51.0,@aws-cdk/aws-applicationautoscaling=1.51.0,@aws-cdk/aws-autoscaling-common=1.51.0,@aws-cdk/aws-cloudwatch=1.51.0,@aws-cdk/aws-dynamodb=1.51.0,@aws-cdk/aws-ec2=1.51.0,@aws-cdk/aws-events=1.51.0,@aws-cdk/aws-iam=1.51.0,@aws-cdk/aws-kms=1.51.0,@aws-cdk/aws-lambda=1.51.0,@aws-cdk/aws-logs=1.51.0,@aws-cdk/aws-s3=1.51.0,@aws-cdk/aws-s3-assets=1.51.0,@aws-cdk/aws-sqs=1.51.0,@aws-cdk/aws-ssm=1.51.0,@aws-cdk/cloud-assembly-schema=1.51.0,@aws-cdk/core=1.51.0,@aws-cdk/custom-resources=1.51.0,@aws-cdk/cx-api=1.51.0,@aws-cdk/region-info=1.51.0,jsii-runtime=node.js/v12.18.2
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18eS3BucketCFDE3952:
    Type: String
    Description: S3 bucket for asset "6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18e"
  AssetParameters6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18eS3VersionKeyBCDB680B:
    Type: String
    Description: S3 key for asset version "6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18e"
  AssetParameters6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18eArtifactHash080B82E1:
    Type: String
    Description: Artifact hash for asset "6a7d873afb9708c54a028397815847798167997a92acf973f48ca7887265c18e"
Outputs:
  GatewayhelloEndpoint0AD6BE83:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: Gatewayhello270BBC94
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: GatewayhelloDeploymentStageprod042FD68F
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

